### ISSUE TITLE
Ophicleide app is crashed after requested the main page

### ISSUE THREAD

**Issue by olegvn88** [ophicleide/ophicleide-training#23]
Ophicleide app is crashed after the main page is opened.

I guess the problem caused by old version of spark. Oshinko provides spark version 2.3, but in ophicleide-training Docker file uses oshinko spark version 2.2
https://github.com/ophicleide/ophicleide-training/blob/develop/Dockerfile

![ophicleide_pod_crashed](https://user-images.githubusercontent.com/20247663/43398154-e34fa404-940f-11e8-9ba1-95c8c0aa9b20.png)

Here log from ophicleide-web pod:
Environment: 
	DEV_MODE=false
	NODE_ENV=production
	DEBUG_PORT=5858
Launching via npm...
npm info it worked if it ends with ok
npm info using npm@2.15.1
npm info using node@v4.6.2
npm info prestart ophicleide-web@0.0.0
> ophicleide-web@0.0.0 start /opt/app-root/src
> node server.js
npm info start ophicleide-web@0.0.0
ophicleide-web listening on 8081
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: connect ECONNREFUSED 127.0.0.1:8080
    at Object.exports._errnoException (util.js:911:11)
    at exports._exceptionWithHostPort (util.js:934:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1076:14)
npm info ophicleide-web@0.0.0 Failed to exec start script
npm ERR! Linux 3.10.0-862.el7.x86_64
npm ERR! argv "/opt/rh/rh-nodejs4/root/usr/bin/node" "/opt/rh/rh-nodejs4/root/usr/bin/npm" "run" "-d" "start"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! ophicleide-web@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ophicleide-web@0.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the ophicleide-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ophicleide-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ophicleide-web
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR! /opt/app-root/src/npm-debug.log

**Comment by elmiko** [comment]
i think even with the upgraded spark image that this will still crash in the tutorial deployment. spark 2.3 changed the way that the workers communicate with the driver and i think we will need to add something similar to the headless services in order for the workers to have proper communication with the driver.

probably we need to upgrade this application to use source-to-image to work around these issues.

**Comment by elmiko** [comment]
confirmed, this change is passing the tests.
